[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.135.0"

[[redirects]]
  from = "/ueber-mich/"
  to = "/ueber/"
  status = 301

[[redirects]]
  from = "/counter/count.js"
  to = "https://gc.zgo.at/count.js"
  status = 200
  force = true

[[redirects]]
  from = "/counter/count"
  to = "https://mafrei.goatcounter.com/count"
  status = 200
  force = true
